import type {NextPage} from 'next'
import Head from 'next/head'
import {connect} from 'react-redux'
import {wrapper} from "@yuyuid/src/redux/store";
import {ChangeModeTheme} from "@yuyuid/redux";

const Components = connect((state) => {
  return {state}
})(function (props: any) {
  return (
    <div>
      <pre>{JSON.stringify(props, null, 2)}</pre>
    </div>
  )
})

const Home: NextPage = ((props: any) => {
  let {preloadState,uuid} = props
  //TODO: if you use ServerSideProps in page recommendation use hooks
  // UpdateStateHook(preloadState)


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <pre>{JSON.stringify(props,null,2)}</pre>
        <Components/>
      </main>
    </div>
  )
})

export const getServerSideProps = wrapper.getServerSideProps(
  // @ts-ignore
  (store) => async (ctx) => {
    store.dispatch(ChangeModeTheme({mode: "dark"}))
    //@ts-ignore
    return {
      props: {
        preloadState: store.getState()
      }
    }
  })
export default Home
